//CONTENT
export const GET_CATEGORIES = 'CONTENT/GET_CATEGORIES';
export const GET_ELEMENTS = 'CONTENT/GET_ELEMENTS';
export const GET_CATEGORY = 'CONTENT/GET_CATEGORY';
export const GET_ELEMENT = 'CONTENT/GET_ELEMENT';

export const REQUEST_CATEGORIES = 'CONTENT/REQUEST_CATEGORIES';
export const REQUEST_CATEGORY = 'CONTENT/REQUEST_CATEGORY';
export const REQUEST_ELEMENT = 'CONTENT/REQUEST_ELEMENT';

//APP
export const SET_ERROR = 'APP/SET_ERROR';
export const CLEAN_ERROR = 'APP/CLEAN_ERROR';
