export const GET_CATEGORIES = 'CONTENT/GET_CATEGORIES';
export const GET_ELEMENTS = 'CONTENT/GET_ELEMENTS';
export const GET_CATEGORY = 'CONTENT/GET_CATEGORY';
export const GET_ELEMENT = 'CONTENT/GET_ELEMENT';
